name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Test
      run: |
          mkdir -p artifacts
          env | tee > artifacts/env.txt
          sudo lshw | tee artifacts/lshw.txt
          sudo tar zcvf artifacts/etc.tar.gz /etc
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}
        path: artifacts
