name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test
      run: |
          mkdir -p artifacts
          env | tee > artifacts/env.txt
          # sudo lshw | tee artifacts/lshw.txt
          # sudo tar zcvf artifacts/etc.tar.gz /etc
          sleep 60
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}
        path: artifacts
