on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: |
        ls -lsa $GITHUB_STEP_SUMMARY
        echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "::notice title=Build information::Build: 2024-03-30 16:36:22 202aaf1 amd64 ci gha jammy ubuntu"
        echo "::notice title=Build information::506880 -rw-r--r-- 1 root root 519045120 Mar 30 16:36 /home/runner/work/finnix-live-build/finnix-live-build/build/lb/finnix-amd64.hybrid.iso"
        echo "::notice title=Build information::a5ae8e081a9707e8ce995a5f08067afdf33bbc39b00b6019a3c8f4ee3c3c97324178894878ef9e2a7a26b76c2109696ed4d3ebc3448d58b61bb126978ae0ca7a  /home/runner/work/finnix-live-build/finnix-live-build/build/lb/finnix-amd64.hybrid.iso"
        sudo env | sort
        echo "============================================="
        env | grep ^GITHUB_ | sudo tee -a /etc/environment >/dev/null
        sudo env | sort
        cat <<EOM >~/.testheredoc
        foo
        ${BASH_VERSION}
        bar
        EOM
        cat ~/.testheredoc
    #- name: Python 3.9
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: 3.9
    - name: Test
      run: |
          #ls -lsa /opt/hostedtoolcache
          #ls /opt/hostedtoolcache/Python
          #ls /opt/hostedtoolcache/Python/3.9.12/x64
          mkdir -p artifacts
          env | sort | tee artifacts/env.txt
          ls -lsa /home/runner/runners/*/
          cat /home/runner/runners/*/.setup_info
          cat /etc/passwd
          cat /etc/group
          id
          pwd
          #python --version
          dpkg -l
          # sudo lshw | tee artifacts/lshw.txt
          # sudo tar zcvf artifacts/etc.tar.gz /etc
          # sleep 60
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}
        path: artifacts
