name: ci
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: |
        sudo env | sort
        echo "============================================="
        env | grep ^GITHUB_ | sudo tee -a /etc/environment >/dev/null
        sudo env | sort
        cat <<EOM >~/.testheredoc
        foo
        ${BASH_VERSION}
        bar
        EOM
        cat ~/.testheredoc
    #- name: Python 3.9
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: 3.9
    - name: Test
      run: |
          #ls -lsa /opt/hostedtoolcache
          #ls /opt/hostedtoolcache/Python
          #ls /opt/hostedtoolcache/Python/3.9.12/x64
          mkdir -p artifacts
          env | sort | tee artifacts/env.txt
          ls -lsa /home/runner/runners/*/
          cat /home/runner/runners/*/.setup_info
          cat /etc/passwd
          cat /etc/group
          id
          pwd
          #python --version
          dpkg -l
          # sudo lshw | tee artifacts/lshw.txt
          # sudo tar zcvf artifacts/etc.tar.gz /etc
          # sleep 60
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}
        path: artifacts
