name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Dependency packages
      run: sudo apt -y install build-essential debhelper/bionic-backports git-buildpackage po4a gettext man-db debian-archive-keyring librsvg2-bin fonts-liberation2 python3-jinja2
    - name: Build / install live-build
      run: |
        sudo rm -f /usr/bin/checkbashisms
        cd live-build
        gbp buildpackage --git-ignore-branch
        sudo apt -y install ../*.deb
    - name: Build image
      run: sudo ./finnix-live-build
