name: userland-arm64
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependency packages
      run: sudo apt-get -y install build-essential cmake gcc-aarch64-linux-gnu libc6-dev-arm64-cross
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=None -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DARM64=ON
    - name: make
      run: make -j2
    - name: make install
      run: mkdir -p ${GITHUB_WORKSPACE}/destdir && make install DESTDIR==${GITHUB_WORKSPACE}/destdir
    - name: Build tarball
      run: mkdir -p ${GITHUB_WORKSPACE}/artifacts && tar -C ${GITHUB_WORKSPACE}/destdir zcvf ${GITHUB_WORKSPACE}/artifacts/${{ github.job }}-${{ github.run_id }}.${{ github.run_number }}.tar.gz
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}-${{ github.run_id }}.${{ github.run_number }}
        path: artifacts/*.tar.gz
